import Head from 'next/head';
import {useRouter} from 'next/router';
import {Grid, Button} from '@material-ui/core';
import AnalogyCard from '../components/analogyCard';
import InfoCard from '../components/infoCard';

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className = "diceGrid1">
        <Grid container>
          <Grid item xs = {1} sm = {2} md = {3}></Grid>
          <Grid item xs = {10} sm = {8} md = {6}>
            <AnalogyCard />
          </Grid>
          <Grid item xs = {1} sm = {2} md = {3}></Grid>
        </Grid>
      </div>
    </div>
  )
}
