import Head from 'next/head';
import {useRouter} from 'next/router';
import {Grid, Button} from '@material-ui/core';
import SwapCard from '../components/swapCard';
import InfoCard from '../components/infoCard';

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className = "diceGrid1">
      <Grid container spacing = {3}>

        <Grid item xs = {1} sm = {2} md = {2}></Grid>
        <Grid item xs = {10} sm = {8} md = {8}>
            <div style={{marginTop:'17%'}}>
                {/* <span style={{color:'#d13737', fontSize:14}}>S O M E T H I N G</span> */}
                <p style={{color:'white',fontSize:50}}>Atari decentralized <br /> Exchange </p>
                {/* <p style={{color:'rgb(255,255,255,0.4)', fontSize:16}}>The kjakaf aikaav advoav avadv adoadoavanaoa ajadova <br />
                    aoa jf v o adjavk advkadv ajfvjf vkjev ajafjvveg egege<br />
                    k advkadv ajfvjf vkjev ajafjvveg</p>
                <button variant="contained" className="home_button">Try it free </button> */}
            </div>
        </Grid>
        <Grid item xs = {1} sm = {1} md = {1}></Grid>
    </Grid>
      </div>
    </div>
  )
}
