import Head from 'next/head';
import {useRouter} from 'next/router';
import styles from '../styles/Home.module.css';
import {Grid, Button} from '@material-ui/core';
import LiquidityCard from '../components/liquidityCard';

export default function Home() {
const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className = "diceGrid1">
        {/* <Grid container className = "text-center mb-5">
          <Grid item xs = {1} sm = {2} md = {4}></Grid>
          <Grid item xs = {10} sm = {8} md = {4} className = "x-home-top-container">
          <Button variant = "outlined" className = "x-home-top-button x-font3" onClick = {()=>router.push("/swap")}>Swap</Button>
            <Button variant = "outlined" className = "x-home-top-button x-font3" onClick = {()=>router.push("/liquidity")}>Liquidity</Button>
            <Button variant = "outlined" className = "x-home-top-button x-font3" onClick = {()=>router.push("/stake")}>Stake</Button>
            <Button variant = "outlined" className = "x-home-top-button x-font3" onClick = {()=>router.push("/buy")}>Buy</Button>
          </Grid>
          <Grid item xs = {1} sm = {2} md = {4}></Grid>
        </Grid> */}
        <Grid container>
          <Grid item xs = {1} sm = {2} md = {4}></Grid>
          <Grid item xs = {10} sm = {8} md = {4}>
            <LiquidityCard />
          </Grid>
          <Grid item xs = {1} sm = {2} md = {4}></Grid>
        </Grid>
      </div>
    </div>
  )
}
